# Generated by Django 4.2.4 on 2023-09-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('type', models.CharField(max_length=100, verbose_name='Тип техники')),
                ('amount', models.CharField(max_length=100, verbose_name='Количество')),
                ('inventory_number', models.CharField(max_length=100, verbose_name='Инвентарный номер')),
                ('manufacture_number', models.CharField(max_length=100, verbose_name='Заводской номер')),
                ('residual_value', models.IntegerField(verbose_name='Остаточная стоимость')),
                ('date_of_manufacture', models.DateField(verbose_name='Дата производства')),
                ('date_of_purchase', models.DateField(verbose_name='Дата покупки')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('country_of_manufacture', models.CharField(max_length=100, verbose_name='Страна производства')),
            ],
        ),
        migrations.CreateModel(
            name='types_directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='Название типа техники')),
                ('dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.directory')),
            ],
        ),
        migrations.CreateModel(
            name='countries_directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, verbose_name='Название страны')),
                ('country_code', models.IntegerField(verbose_name='Код страны')),
                ('dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.directory')),
            ],
        ),
    ]
